export const Donors = [
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        bloodType: "O+",
        state: "UttarPradesh",
        district: "Mau",
        status: "registered",
        address: "Rohini Sector 22, 110086, New Delhi",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        bloodType: "O+",
        state: "UttarPradesh",
        district: "Mau",
        status: "verified",
        address: "Rohini Sector 22, 110086, New Delhi",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        bloodType: "O+",
        state: "UttarPradesh",
        district: "Mau",
        status: "donated",
        address: "Rohini Sector 22, 110086, New Delhi",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        bloodType: "O+",
        state: "UttarPradesh",
        district: "Mau",
        status: "registered",
        address: "Rohini Sector 22, 110086, New Delhi",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        bloodType: "O+",
        state: "UttarPradesh",
        district: "Mau",
        address: "Rohini Sector 22, 110086, New Delhi",
        status: "verified",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        bloodType: "O+",
        address: "Rohini Sector 22, 110086, New Delhi",
        state: "UttarPradesh",
        district: "Mau",
        status: "donated",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },    {
        fname: "Kartik",
        lname: "Rai",
        address: "Rohini Sector 22, 110086, New Delhi",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        bloodType: "O+",
        state: "UttarPradesh",
        district: "Mau",
        status: "registered",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        address: "Rohini Sector 22, 110086, New Delhi",
        gender: "Male",
        bloodType: "O+",
        state: "UttarPradesh",
        district: "Mau",
        status: "verified",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        address: "Rohini Sector 22, 110086, New Delhi",
        bloodType: "O+",
        state: "UttarPradesh",
        district: "Mau",
        status: "donated",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        bloodType: "O+",
        address: "Rohini Sector 22, 110086, New Delhi",
        state: "UttarPradesh",
        district: "Mau",
        status: "registered",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        bloodType: "O+",
        address: "Rohini Sector 22, 110086, New Delhi",
        state: "UttarPradesh",
        district: "Mau",
        status: "verified",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        bloodType: "O+",
        address: "Rohini Sector 22, 110086, New Delhi",
        state: "UttarPradesh",
        district: "Mau",
        status: "donated",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        address: "Rohini Sector 22, 110086, New Delhi",
        bloodType: "O+",
        state: "UttarPradesh",
        district: "Mau",
        status: "registered",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        bloodType: "O+",
        state: "UttarPradesh",
        address: "Rohini Sector 22, 110086, New Delhi",
        district: "Mau",
        status: "verified",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        bloodType: "O+",
        state: "UttarPradesh",
        district: "Mau",
        status: "donated",
        address: "Rohini Sector 22, 110086, New Delhi",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        bloodType: "O+",
        state: "UttarPradesh",
        district: "Mau",
        address: "Rohini Sector 22, 110086, New Delhi",
        status: "registered",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        bloodType: "O+",
        address: "Rohini Sector 22, 110086, New Delhi",
        state: "UttarPradesh",
        district: "Mau",
        status: "verified",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        address: "Rohini Sector 22, 110086, New Delhi",
        bloodType: "O+",
        state: "UttarPradesh",
        district: "Mau",
        status: "donated",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        address: "Rohini Sector 22, 110086, New Delhi",
        bloodType: "O+",
        state: "UttarPradesh",
        district: "Mau",
        status: "registered",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        address: "Rohini Sector 22, 110086, New Delhi",
        gender: "Male",
        bloodType: "O+",
        state: "UttarPradesh",
        district: "Mau",
        status: "verified",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Kartik",
        lname: "Rai",
        email: "kartikrai0912@gmail.com",
        contact: "+91 8690625956",
        dob: "09/12/2002",
        gender: "Male",
        address: "Rohini Sector 22, 110086, New Delhi",
        bloodType: "O+",
        state: "UttarPradesh",
        district: "Mau",
        status: "donated",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },

];

export const Recipients = [
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        address: "Rohini Sector 22, 110086, New Delhi",
        gender: "Male",
        bloodType: "AB+",
        state: "UttarPradesh",
        district: "Mau",
        status: "registered",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        address: "Rohini Sector 22, 110086, New Delhi",
        gender: "Male",
        bloodType: "AB+",
        state: "UttarPradesh",
        district: "Mau",
        status: "verified",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        address: "Rohini Sector 22, 110086, New Delhi",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        bloodType: "AB+",
        state: "UttarPradesh",
        district: "Mau",
        status: "recieved",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        bloodType: "AB+",
        address: "Rohini Sector 22, 110086, New Delhi",
        state: "UttarPradesh",
        district: "Mau",
        status: "registered",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        bloodType: "AB+",
        address: "Rohini Sector 22, 110086, New Delhi",
        state: "UttarPradesh",
        district: "Mau",
        status: "verified",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        bloodType: "AB+",
        state: "UttarPradesh",
        address: "Rohini Sector 22, 110086, New Delhi",
        district: "Mau",
        status: "recieved",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        bloodType: "AB+",
        state: "UttarPradesh",
        address: "Rohini Sector 22, 110086, New Delhi",
        district: "Mau",
        status: "registered",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        bloodType: "AB+",
        address: "Rohini Sector 22, 110086, New Delhi",
        state: "UttarPradesh",
        district: "Mau",
        status: "verified",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        bloodType: "AB+",
        state: "UttarPradesh",
        address: "Rohini Sector 22, 110086, New Delhi",
        district: "Mau",
        status: "recieved",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        address: "Rohini Sector 22, 110086, New Delhi",
        bloodType: "AB+",
        state: "UttarPradesh",
        district: "Mau",
        status: "registered",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        address: "Rohini Sector 22, 110086, New Delhi",
        bloodType: "AB+",
        state: "UttarPradesh",
        district: "Mau",
        status: "verified",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        address: "Rohini Sector 22, 110086, New Delhi",
        dob: "24/01/2001",
        gender: "Male",
        bloodType: "AB+",
        state: "UttarPradesh",
        district: "Mau",
        status: "recieved",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        bloodType: "AB+",
        address: "Rohini Sector 22, 110086, New Delhi",
        state: "UttarPradesh",
        district: "Mau",
        status: "registered",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        address: "Rohini Sector 22, 110086, New Delhi",
        bloodType: "AB+",
        state: "UttarPradesh",
        district: "Mau",
        status: "verified",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        address: "Rohini Sector 22, 110086, New Delhi",
        gender: "Male",
        bloodType: "AB+",
        state: "UttarPradesh",
        district: "Mau",
        status: "recieved",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        bloodType: "AB+",
        state: "UttarPradesh",
        address: "Rohini Sector 22, 110086, New Delhi",
        district: "Mau",
        status: "registered",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        bloodType: "AB+",
        state: "UttarPradesh",
        address: "Rohini Sector 22, 110086, New Delhi",
        district: "Mau",
        status: "verified",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        bloodType: "AB+",
        state: "UttarPradesh",
        district: "Mau",
        address: "Rohini Sector 22, 110086, New Delhi",
        status: "recieved",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        bloodType: "AB+",
        state: "UttarPradesh",
        district: "Mau",
        status: "registered",
        address: "Rohini Sector 22, 110086, New Delhi",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        address: "Rohini Sector 22, 110086, New Delhi",
        bloodType: "AB+",
        state: "UttarPradesh",
        district: "Mau",
        status: "verified",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        bloodType: "AB+",
        address: "Rohini Sector 22, 110086, New Delhi",
        state: "UttarPradesh",
        district: "Mau",
        status: "recieved",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        bloodType: "AB+",
        address: "Rohini Sector 22, 110086, New Delhi",
        state: "UttarPradesh",
        district: "Mau",
        status: "registered",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        dob: "24/01/2001",
        gender: "Male",
        address: "Rohini Sector 22, 110086, New Delhi",
        bloodType: "AB+",
        state: "UttarPradesh",
        district: "Mau",
        status: "verified",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    {
        fname: "Jatin",
        lname: "Khandelwal",
        email: "khandelwaljatin2401@gmail.com",
        contact: "+91 9532701690",
        address: "Rohini Sector 22, 110086, New Delhi",
        dob: "24/01/2001",
        gender: "Male",
        bloodType: "AB+",
        state: "UttarPradesh",
        district: "Mau",
        status: "recieved",
        medicalHistory: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore aperiam quos molestiae fuga eaque omnis tenetur repellendus, magnam similique dolore officiis aliquid reiciendis! Quo dolorem tempora totam animi, perferendis praesentium!",
    },
    
]